:main_frame:
  :positions:
    :x: 10
    :y: 10
    :width: 170
    :height: 60

:forms:
  :login:
    :type: :select
    :positions:
      :x: 10
      :y: 10
      :width: 100
      :height: 50
    :elements:
      - :id: 1
        :type: button
        :attributes:
          :is_selectable: 1
          :is_clickable: 0
          :selected_title: '->new'
          :action_end_info:
            :move_next: 1
            :move_next_action_id: 0
          :object_name: 'signup_button'

        :text_colour: red
        :title: '  new'
        :h: 10
        :w: 20
        :x: 5
        :y: 5
  
      - :id: 2
        :type: button
        :attributes:
          :is_selectable: 1
          :is_clickable: 0
          :selected_title: '->continue'
          :action_end_info:
            :move_next: 1
            :move_next_action_id: 1
          :object_name: 'signin_button'
        :title: '  continue'
        :h: 10
        :w: 20
        :x: 5
        :y: 15 

  :create_user:
    :type: :input
    :positions:
      :x: 10
      :y: 10
      :width: 100
      :height: 50
    :elements:
      - :id: 0
        :type: :input
        :title: 'user name'
        :attributes:
          :is_selectable: 1
          :is_clickable: 0
          :selected_title: '->user name'
          :text_colour: red
          :object_name: 'user_name'
        :h: 15
        :w: 20
        :x: 5
        :y: 5
      - :id: 1
        :type: :input
        :title: '  PASS'
        :attributes:
          :is_selectable: 1
          :is_clickable: 0
          :selected_title: '->PASS'
          :text_colour: red
          :object_name: 'password'
        :h: 15
        :w: 20
        :x: 5
        :y: 15
      - :id: 2 
        :type: button
        :title: '  submit'
        :h: 10
        :w: 20
        :x: 5
        :y: 25
        :attributes:
          :is_selectable: 1
          :is_clickable: 0
          :selected_title: '->submit<-'
          :action_end_info:
            :move_next: 1
            :move_next_action_id: 1
          :object_name: 'submit_button'
      - :id: 3 
        :type: :test
        :title: 'test'
        :h: 10 
        :w: 20
        :x: 5
        :y: 30
        :attributes:
          :is_test: 1
          :is_selectable: 0
          :is_clickable: 0
          :selected_title: '->ID'
          :text_colour: red
          :object_name: 'test_text'
  
  
