:main_frame:
  :positions:
    :x: 10
    :y: 10
    :width: 170
    :height: 40

:forms:
  :login:
    :type: :select
    :positions:
      :x: 10
      :y: 10
      :width: 50
      :height: 20
    :elements:
      - :id: 1
        :type: button
        :attributes:
          :is_selectable: 0
          :is_clickable: 0
          :selected_title: '->new'
          :move_next: 1
          :move_next_action_id: 0
        :text_colour: red
        :title: '  new'
        :h: 10
        :w: 20
        :x: 5
        :y: 5
  
      - :id: 2
        :type: button
        :attributes:
          :is_selectable: 0
          :is_clickable: 0
          :selected_title: '->continue'
          :move_next: 1
          :move_next_action_id: 1
        :title: '  continue'
        :h: 10
        :w: 20
        :x: 5
        :y: 25 

  :create_user:
    :type: :input
    :positions:
      :x: 10
      :y: 40
      :width: 50
      :height: 50
    :elements:
      - :id: 0
        :type: :input
        :is_selectable: 0
        :text_colour: red
        :title: '  user_name'
        :selected_title: '->user_name'
        :x: 15
        :y: 25
        :width: 15
  
  
