:main_frame:
  :positions:
    :x: 10
    :y: 10
    :width: 170
    :height: 40

:forms:
  :login:
    :type: :select
    :positions:
      :x: 10
      :y: 10
      :width: 20
      :height: 20
    :elements:
      - :id: 0
        :selective: 0
        :text_colour: red
        :title: '  new'
        :selected_title: '->new'
        :x: 5
        :y: 5
  
      - :id: 0
        :selective: 1
        :title: '  new'
        :selected_title: '->new'
        :x: 5
        :y: 5
      - :id: 1
        :selective: 1
        :title: '  continue'
        :selected_title: '->continue'
        :x: 5
        :y: 6
  :create_user:
    :type: :input
    :positions:
      :x: 10
      :y: 40
      :width: 50
      :height: 50
    :elements:
      - :id: 0
        :type: :input
        :selective: 0
        :text_colour: red
        :title: '  user_name'
        :selected_title: '->user_name'
        :x: 15
        :y: 25
        :width: 15
  
  
